services:
  jdownloader:
    image: antlafarge/jdownloader:latest
    container_name: jdownloader
    restart: unless-stopped
    user: "1000:10"
    volumes:
      - "/volume1/Default-volume-1/0001_Docker/jdownloader:/jdownloader/downloads/"
      - "/volume2/docker/jdownloader/config:/jdownloader/cfg/"
      - "/volume2/docker/jdownloader/logs:/jdownloader/logs/"
    environment:
      TZ: "Europe/Zurich"
    secrets:
      - JD_EMAIL
      - JD_PASSWORD
      - JD_DEVICENAME
    networks:
      - jd_custom_network

secrets:
  JD_EMAIL:
    file: /volume2/docker/jdownloader/secrets/jd_email.txt
  JD_PASSWORD:
    file: /volume2/docker/jdownloader/secrets/jd_password.txt
  JD_DEVICENAME:
    file: /volume2/docker/jdownloader/secrets/jd_devicename.txt

networks:
  jd_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.10.0/24 
