services:
  jdownloader:
    image: antlafarge/jdownloader:latest
    container_name: jdownloader
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    volumes:
      - "${DOCKER_DATA_DIR}/jdownloader:/jdownloader/downloads/"
      - "${DOCKER_CONFIG_DIR}/jdownloader/config:/jdownloader/cfg/"
      - "${DOCKER_CONFIG_DIR}/jdownloader/logs:/jdownloader/logs/"
    environment:
      TZ: "${TZ}"
    secrets:
      - JD_EMAIL
      - JD_PASSWORD
      - JD_DEVICENAME
    networks:
      - jd_custom_network

secrets:
  JD_EMAIL:
    file: ${DOCKER_CONFIG_DIR}/jdownloader/secrets/jd_email.txt
  JD_PASSWORD:
    file: ${DOCKER_CONFIG_DIR}/jdownloader/secrets/jd_password.txt
  JD_DEVICENAME:
    file: ${DOCKER_CONFIG_DIR}/jdownloader/secrets/jd_devicename.txt

networks:
  jd_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.10.0/24
