services:
  actualtap:
    container_name: actualtap
    image: mattyfaz/actualtap:latest
    restart: unless-stopped

    network_mode: host
    environment:
      - TZ=${TZ}
      - ACTUAL_URL=${ACTUAL_URL}
      - ACTUAL_PASSWORD=${ACTUAL_PASSWORD}
      - ACTUAL_SYNC_ID=${ACTUAL_SYNC_ID}
      - API_KEY=${API_KEY}
      - ACTUAL_ENCRYPTION_PASSWORD=${ACTUAL_ENCRYPTION_PASSWORD}

    labels:
      traefik.enable: "true"
      traefik.http.routers.actual-tap.rule: "Host(`${ACTUAL_TAP_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.actual-tap.entrypoints: "${TRAEFIK_ENTRYPOINT_1}"
      traefik.http.routers.actual-tap.tls: "true"
      traefik.http.routers.actual-tap.service: "actual-tap"
      traefik.http.routers.actual-tap.middlewares: "hsts-headers@docker"
      traefik.http.services.actual-tap.loadbalancer.server.url: "http://host.docker.internal:3001"
      traefik.http.routers.actual-tap-private.rule: "Host(`${ACTUAL_TAP_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.actual-tap-private.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.actual-tap-private.tls: "true"
      traefik.http.routers.actual-tap-private.service: "actual-tap-private"
      traefik.http.routers.actual-tap-private.middlewares: "hsts-headers@docker"
      traefik.http.services.actual-tap-private.loadbalancer.server.url: "http://host.docker.internal:3001"
