services:
  audiobookshelf:
    container_name: audiobookshelf
    image: advplyr/audiobookshelf
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - ${DOCKER_CONFIG_DIR}/audiobookshelf:/config:rw
      - ${DOCKER_DATA_DIR}/audiobookshelf/audiobooks:/audiobooks:rw
      - ${DOCKER_DATA_DIR}/audiobookshelf/podcasts:/podcasts:rw
      - ${DOCKER_CONFIG_DIR}/audiobookshelf/metadata:/metadata:rw
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - cloudflare_web_network

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
