services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${DOCKER_CONFIG_DIR}/plex/config:/config
      - ${DOCKER_DATA_DIR}/jellyfin/tv-shows:/tv
      - ${DOCKER_DATA_DIR}/jellyfin/movies:/movie
    networks:
      - cloudflare_web_network
    restart: unless-stopped

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
