services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    user: "0:0"
    expose:
      - "80"
    volumes:
      - /volume2/docker/filebrowser/database:/database
      - /volume2/docker/filebrowser/config:/config
      - /:/srv
    command: --database /database/filebrowser.db --root /srv --port 80
    networks:
      - cloudflare_web_network

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
