services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome
    mem_limit: 6g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - ${DOCKER_CONFIG_DIR}/navidrome:/data:rw
      - ${DOCKER_CONFIG_DIR}/navidrome/music-root:/music:rw

      # Music locations, put as many as needed
      - ${MUSIC_DIR_1}:/music/user1:ro
      - ${MUSIC_DIR_2}:/music/user2:ro
      - ${MUSIC_DIR_3}:/music/user3:ro

      - ${DOCKER_CONFIG_DIR}/navidrome/empty-library-fallback:/empty:rw
      - ${DOCKER_CONFIG_DIR}/navidrome/cache:/var/cache/navidrome:rw
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      ND_ENABLEINSIGHTSCOLLECTOR: false
      ND_MUSICFOLDER: /music
    networks:
      - cloudflare_web_network

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
