services:
  openresume:
    container_name: open-resume
    image: peppershade/open-resume:latest
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - cloudflare_web_network
      - traefik_proxy_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.openresume.rule: "Host(`${OPENRESUME_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.openresume.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.openresume.tls: "true"
      traefik.http.routers.openresume.service: "openresume"
      traefik.http.routers.openresume.middlewares: "hsts-headers@docker"
      traefik.http.routers.openresume-tailnet.rule: "Host(`${OPENRESUME_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.openresume-tailnet.entrypoints: "${TRAEFIK_ENTRYPOINT_7}"
      traefik.http.routers.openresume-tailnet.tls: "true"
      traefik.http.routers.openresume-tailnet.service: "openresume"
      traefik.http.routers.openresume-tailnet.middlewares: "hsts-headers@docker,tailnet-admin-only@docker"
      traefik.http.services.openresume.loadbalancer.server.port: "3000"
      traefik.docker.network: "traefik-proxy"

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
  traefik_proxy_network:
    name: traefik-proxy
    external: true
