services:
  gocron:
    image: ghcr.io/flohoss/gocron:latest
    container_name: gocron
    hostname: gocron
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      PORT: 8156
    volumes:
      - ${DOCKER_CONFIG_DIR}/gocron/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cloudflare_web_network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8156/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
