services:
  lifeglance:
    image: ghcr.io/krelltunez/lifeglance:latest
    container_name: Lifeglance
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 6868:80
    restart: on-failure:5
