services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: home-assistant
    mem_limit: 8g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: host
    ports:
      - "8123:8123"
    volumes:
      - ${DOCKER_CONFIG_DIR}/homeassistant:/config:rw
    environment:
      TZ: "${TZ}"
