services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: home-assistant
    mem_limit: 8g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: host
    ports:
      - "8123:8123"
    volumes:
      - ${DOCKER_CONFIG_DIR}/homeassistant:/config:rw
    environment:
      TZ: "${TZ}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homeassistant.rule: "Host(`${HOME_ASSISTANT_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.homeassistant.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.homeassistant.tls: "true"
      traefik.http.routers.homeassistant.service: "homeassistant"
      traefik.http.routers.homeassistant.middlewares: "hsts-headers@docker"
      traefik.http.routers.homeassistant-tailnet.rule: "Host(`${HOME_ASSISTANT_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.homeassistant-tailnet.entrypoints: "${TRAEFIK_ENTRYPOINT_7}"
      traefik.http.routers.homeassistant-tailnet.tls: "true"
      traefik.http.routers.homeassistant-tailnet.service: "homeassistant"
      traefik.http.routers.homeassistant-tailnet.middlewares: "hsts-headers@docker,tailnet-admin-only@docker"
      traefik.http.services.homeassistant.loadbalancer.server.url: "http://host.docker.internal:8123"
