services:
  withoutbg:
    image: withoutbg/app:latest
    container_name: WithoutBG
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: unless-stopped
    networks:
      - cloudflare_web_network
      - traefik_proxy_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.withoutbg.rule: "Host(`${WITHOUTBG_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.withoutbg.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.withoutbg.tls: "true"
      traefik.http.routers.withoutbg.tls.certresolver: "cf_dns"
      traefik.http.routers.withoutbg.service: "withoutbg"
      traefik.http.services.withoutbg.loadbalancer.server.port: "80"
      traefik.docker.network: "traefik-proxy"

networks:
  cloudflare_web_network:
    external: true
    name: cloudflare-web
  traefik_proxy_network:
    external: true
    name: traefik-proxy
