services:
  mini-qr:
    image: ghcr.io/lyqht/mini-qr:latest
    container_name: mini-qr
    restart: unless-stopped
    networks:
      - cloudflare_web_network
      - traefik_proxy_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.mini-qr-private.rule: "Host(`${MINI_QR_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.mini-qr-private.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.mini-qr-private.tls: "true"
      traefik.http.routers.mini-qr-private.tls.certresolver: "cf_dns"
      traefik.http.routers.mini-qr-private.service: "mini-qr"
      traefik.http.routers.mini-qr-private.middlewares: "hsts-headers@docker"
      traefik.http.routers.mini-qr-family.rule: "Host(`${MINI_QR_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.mini-qr-family.entrypoints: "${TRAEFIK_ENTRYPOINT_1}"
      traefik.http.routers.mini-qr-family.tls: "true"
      traefik.http.routers.mini-qr-family.tls.certresolver: "cf_dns"
      traefik.http.routers.mini-qr-family.service: "mini-qr"
      traefik.http.routers.mini-qr-family.middlewares: "hsts-headers@docker"
      traefik.http.services.mini-qr.loadbalancer.server.port: "8080"
      traefik.docker.network: "traefik-proxy"

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
  traefik_proxy_network:
    name: traefik-proxy
    external: true
