services:
  mini-qr:
    image: ghcr.io/lyqht/mini-qr:latest
    container_name: mini-qr
    restart: unless-stopped
    networks:
      - cloudflare_web_network

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
