services:
  snappymail:
    image: djmaze/snappymail:latest
    container_name: snappymail
    restart: unless-stopped
    volumes:
      - ${DOCKER_CONFIG_DIR}/snappymail:/var/lib/snappymail
    environment:
      - ALLOW_ADMIN_PANEL=1
    networks:
      - cloudflare_web_network

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
