services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONFIG_DIR}/grocy/config:/config
    restart: unless-stopped
    networks:
      - cloudflare_web_network
      - traefik_proxy_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.grocy.rule: "Host(`${GROCY_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.grocy.entrypoints: "${TRAEFIK_ENTRYPOINT_1}"
      traefik.http.routers.grocy.tls: "true"
      traefik.http.routers.grocy.tls.certresolver: "cf_dns"
      traefik.http.routers.grocy.service: "grocy"
      traefik.http.services.grocy.loadbalancer.server.port: "80"
      traefik.http.routers.grocy-private.rule: "Host(`${GROCY_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.grocy-private.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.grocy-private.tls: "true"
      traefik.http.routers.grocy-private.tls.certresolver: "cf_dns"
      traefik.http.routers.grocy-private.service: "grocy-private"
      traefik.http.services.grocy-private.loadbalancer.server.port: "80"
      traefik.docker.network: "traefik-proxy"

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
  traefik_proxy_network:
    name: traefik-proxy
    external: true
