services:
  homebox:
    container_name: homebox
    image: ghcr.io/sysadminsmedia/homebox:latest
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - ${DOCKER_CONFIG_DIR}/homebox:/data:rw
    environment:
      HBOX_LOG_LEVEL: "info"
      HBOX_LOG_FORMAT: "text"
      HBOX_WEB_MAX_UPLOAD_SIZE: "5000"
      HBOX_AUTH_API_KEY_PEPPER: "${HBOX_AUTH_API_KEY_PEPPER}"
      TZ: "${TZ}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homebox.rule: "Host(`${HOMEBOX_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.homebox.entrypoints: "${TRAEFIK_ENTRYPOINT_1}"
      traefik.http.routers.homebox.tls: "true"
      traefik.http.routers.homebox.tls.certresolver: "cf_dns"
      traefik.http.routers.homebox.service: "homebox"
      traefik.http.services.homebox.loadbalancer.server.port: "7745"
      traefik.http.routers.homebox-private.rule: "Host(`${HOMEBOX_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.homebox-private.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.homebox-private.tls: "true"
      traefik.http.routers.homebox-private.tls.certresolver: "cf_dns"
      traefik.http.routers.homebox-private.service: "homebox-private"
      traefik.http.services.homebox-private.loadbalancer.server.port: "7745"
      traefik.docker.network: "traefik-proxy"
    networks:
      - cloudflare_web_network
      - traefik_proxy_network

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
  traefik_proxy_network:
    name: traefik-proxy
    external: true
