services:
  webcheck:
    container_name: Web-Check
    image: lissy93/web-check
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - cloudflare_web_network

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
