services:
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:5
    container_name: UpSnap
    mem_limit: 512m
    cpu_shares: 768
    healthcheck:
      test: curl -f http://localhost:8090/ || exit 1
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - UPSNAP_PORT=8090
    volumes:
      - ${DOCKER_CONFIG_DIR}/upsnap:/app/pb_data:rw
    labels:
      traefik.enable: "true"
      traefik.http.routers.upsnap.rule: "Host(`${UPSNAP_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.upsnap.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.upsnap.tls: "true"
      traefik.http.routers.upsnap.tls.certresolver: "cf_dns"
      traefik.http.routers.upsnap.service: "upsnap"
      traefik.http.routers.upsnap.middlewares: "hsts-headers@docker"
      traefik.http.services.upsnap.loadbalancer.server.url: "http://host.docker.internal:8090"

