services:
  glances:
    container_name: Glances
    image: nicolargo/glances:latest-full
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    pid: host
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      GLANCES_OPT: "-w"
      TZ: "${TZ}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.glances.rule: "Host(`${GLANCES_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.glances.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.glances.tls: "true"
      traefik.http.routers.glances.service: "glances"
      traefik.http.routers.glances.middlewares: "hsts-headers@docker"
      traefik.http.routers.glances-tailnet.rule: "Host(`${GLANCES_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.glances-tailnet.entrypoints: "${TRAEFIK_ENTRYPOINT_7}"
      traefik.http.routers.glances-tailnet.tls: "true"
      traefik.http.routers.glances-tailnet.service: "glances"
      traefik.http.routers.glances-tailnet.middlewares: "hsts-headers@docker,tailnet-admin-only@docker"
      traefik.http.services.glances.loadbalancer.server.url: "http://host.docker.internal:61208"
