services:
  surmai:
    image: ghcr.io/rohitkumbhar/surmai:latest
    container_name: viaggi
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${DOCKER_DATA_DIR}/surmai:/pb_data:rw
    environment:
      SURMAI_ADMIN_EMAIL: "${SURMAI_ADMIN_EMAIL}"
      SURMAI_ADMIN_PASSWORD: "${SURMAI_ADMIN_PASSWORD}"
      PB_DATA_DIRECTORY: /pb_data
    restart: unless-stopped
    networks:
      - cloudflare_web_network
      - traefik_proxy_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.surmai-family.rule: "Host(`${SURMAI_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.surmai-family.entrypoints: "${TRAEFIK_ENTRYPOINT_1}"
      traefik.http.routers.surmai-family.tls: "true"
      traefik.http.routers.surmai-family.tls.certresolver: "cf_dns"
      traefik.http.routers.surmai-family.service: "surmai"
      traefik.http.routers.surmai-family.middlewares: "hsts-headers@docker"
      traefik.http.routers.surmai-guest.rule: "Host(`${SURMAI_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.surmai-guest.entrypoints: "${TRAEFIK_ENTRYPOINT_2}"
      traefik.http.routers.surmai-guest.tls: "true"
      traefik.http.routers.surmai-guest.tls.certresolver: "cf_dns"
      traefik.http.routers.surmai-guest.service: "surmai"
      traefik.http.routers.surmai-guest.middlewares: "hsts-headers@docker"
      traefik.http.routers.surmai-friends.rule: "Host(`${SURMAI_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.surmai-friends.entrypoints: "${TRAEFIK_ENTRYPOINT_4}"
      traefik.http.routers.surmai-friends.tls: "true"
      traefik.http.routers.surmai-friends.tls.certresolver: "cf_dns"
      traefik.http.routers.surmai-friends.service: "surmai"
      traefik.http.routers.surmai-friends.middlewares: "hsts-headers@docker"
      traefik.http.services.surmai.loadbalancer.server.port: "8080"
      traefik.http.routers.surmai-private.rule: "Host(`${SURMAI_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.surmai-private.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.surmai-private.tls: "true"
      traefik.http.routers.surmai-private.tls.certresolver: "cf_dns"
      traefik.http.routers.surmai-private.service: "surmai-private"
      traefik.http.routers.surmai-private.middlewares: "hsts-headers@docker"
      traefik.http.services.surmai-private.loadbalancer.server.port: "8080"
      traefik.docker.network: "traefik-proxy"

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
  traefik_proxy_network:
    name: traefik-proxy
    external: true
