services:
  moocup:
    image: jellydeck/moocup:latest
    container_name: moocup
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: unless-stopped
    networks:
      - cloudflare_web_network
      - traefik_proxy_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.moocup.rule: "Host(`${MOOCUP_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.moocup.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.moocup.tls: "true"
      traefik.http.routers.moocup.service: "moocup"
      traefik.http.routers.moocup.middlewares: "hsts-headers@docker"
      traefik.http.routers.moocup-tailnet.rule: "Host(`${MOOCUP_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.moocup-tailnet.entrypoints: "${TRAEFIK_ENTRYPOINT_7}"
      traefik.http.routers.moocup-tailnet.tls: "true"
      traefik.http.routers.moocup-tailnet.service: "moocup"
      traefik.http.routers.moocup-tailnet.middlewares: "hsts-headers@docker,tailnet-admin-only@docker"
      traefik.http.services.moocup.loadbalancer.server.port: "80"
      traefik.docker.network: "traefik-proxy"

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
  traefik_proxy_network:
    name: traefik-proxy
    external: true
