services:
    db:
        image: postgres:latest
        container_name: sosse-db
        hostname: "${SOSSE_DB_HOSTNAME}"
        user: 999:10
        security_opt:
            - no-new-privileges:true
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "sosse", "-U", "sosseuser"]
            timeout: 45s
            interval: 10s
            retries: 10
        environment:
            POSTGRES_DB: sosse
            POSTGRES_USER: sosseuser
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ${DOCKER_DATA_DIR}/sosse/db:/var/lib/postgresql
        restart: unless-stopped
        networks:
            - cloudflare_web_network

    sosse:
        image: biolds/sosse:pip-compose
        container_name: sosse
        labels:
            traefik.enable: "true"
            traefik.http.routers.sosse.rule: "Host(`${SOSSE_SUBDOMAIN}.${DOMAIN}`)"
            traefik.http.routers.sosse.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
            traefik.http.routers.sosse.tls: "true"
            traefik.http.routers.sosse.tls.certresolver: "cf_dns"
            traefik.http.routers.sosse.service: "sosse"
            traefik.http.services.sosse.loadbalancer.server.port: "80"
            traefik.docker.network: "traefik-proxy"
        healthcheck:
            test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 90s
        environment:
            PUID: 10
            PGID: 1000
            TZ: "${TZ}"
            SOSSE_DB_NAME: sosse
            SOSSE_DB_USER: sosseuser
            SOSSE_DB_PASS: ${SOSSE_DB_PASS}
            SOSSE_DB_HOST: sosse-db
            SOSSE_ALLOWED_HOST: "*"
            SOSSE_SECRET_KEY: ${SOSSE_SECRET_KEY}
            SOSSE_USE_TZ: true
            SOSSE_TIMEZONE: Europe/Zurich
        volumes:
            - ${DOCKER_DATA_DIR}/sosse/app:/var/lib/sosse
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - cloudflare_web_network
            - traefik_proxy_network

networks:
    cloudflare_web_network:
        name: cloudflare-web
        external: true
    traefik_proxy_network:
        name: traefik-proxy
        external: true
