services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "${PUID}:${PGID}"
    volumes:
      - ${DOCKER_CONFIG_DIR}/jellyfin/config:/config
      - ${DOCKER_CONFIG_DIR}/jellyfin/cache:/cache
      - ${DOCKER_DATA_DIR}/jellyfin/movies:/media/movies
      - ${DOCKER_DATA_DIR}/jellyfin/tv-shows:/media/tvshows
    restart: 'unless-stopped'
    environment:
      - TZ=${TZ}
    networks:
      - cloudflare_web_network
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri:/dev/dri

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
