services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:latest
    volumes:
      - ${DOCKER_CONFIG_DIR}/beszel:/beszel_data:rw
    ports:
      - "8096:8090"
    environment:
      - PORT=8090
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.beszel.rule: "Host(`${BESZEL_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.beszel.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.beszel.tls: "true"
      traefik.http.routers.beszel.service: "beszel"
      traefik.http.routers.beszel.middlewares: "hsts-headers@docker"
      traefik.http.services.beszel.loadbalancer.server.port: "8090"
      traefik.docker.network: "traefik-proxy"
    networks:
      - cloudflare_web_network
      - traefik_proxy_network

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: Beszel-Agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_CONFIG_DIR}/beszel/agent:/var/lib/beszel-agent:rw
    environment:
      TOKEN: "${BESZEL_AGENT_TOKEN}"
      HUB_URL: "${BESZEL_HUB_URL}"
      LISTEN: "45876"
      KEY: "${BESZEL_AGENT_KEY}"
      FILESYSTEM: "${BESZEL_FILESYSTEM}"
    restart: unless-stopped
    networks:
      - cloudflare_web_network

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
  traefik_proxy_network:
    name: traefik-proxy
    external: true
