services:
  actual_server:
    image: actualbudget/actual-server:26.8.0
    container_name: ActualBudget
    restart: always
    environment:
      TZ: "${TZ}"
    volumes:
      - ${DOCKER_CONFIG_DIR}/actual-budget/actual-data:/data
    networks:
      - cloudflare_web_network
      - traefik_proxy_network
    ports:
      - "5006:5006"
    labels:
      traefik.enable: "true"
      traefik.http.routers.actual-budget.rule: "Host(`${ACTUAL_BUDGET_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.actual-budget.entrypoints: "${TRAEFIK_ENTRYPOINT_1}"
      traefik.http.routers.actual-budget.tls: "true"
      traefik.http.routers.actual-budget.tls.certresolver: "cf_dns"
      traefik.http.routers.actual-budget.service: "actual-budget"
      traefik.http.services.actual-budget.loadbalancer.server.port: "5006"
      traefik.http.routers.actual-budget-private.rule: "Host(`${ACTUAL_BUDGET_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.actual-budget-private.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.actual-budget-private.tls: "true"
      traefik.http.routers.actual-budget-private.tls.certresolver: "cf_dns"
      traefik.http.routers.actual-budget-private.service: "actual-budget-private"
      traefik.http.services.actual-budget-private.loadbalancer.server.port: "5006"
      traefik.docker.network: "traefik-proxy"

  actual_api:
    image: jhonderson/actual-http-api:26.8.0
    container_name: ActualAPI
    restart: always
    ports:
      - "5007:5007"
    environment:
      PORT: "5007"
      ACTUAL_SERVER_URL: "http://ActualBudget:5006"
      ACTUAL_SERVER_PASSWORD: "${ACTUAL_SERVER_PASSWORD}"
      API_KEY: "${ACTUAL_API_PASSWORD}"
      NODE_OPTIONS: "--max-old-space-size=4096"
      ACTUAL_DATA_DIR: "/data"
    volumes:
      - ${DOCKER_CONFIG_DIR}/actual-budget/api-data:/data
    networks:
      - cloudflare_web_network
      - traefik_proxy_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.actual-api.rule: "Host(`${ACTUAL_API_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.actual-api.entrypoints: "${TRAEFIK_ENTRYPOINT_1}"
      traefik.http.routers.actual-api.tls: "true"
      traefik.http.routers.actual-api.tls.certresolver: "cf_dns"
      traefik.http.routers.actual-api.service: "actual-api"
      traefik.http.services.actual-api.loadbalancer.server.port: "5007"
      traefik.http.routers.actual-api-private.rule: "Host(`${ACTUAL_API_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.actual-api-private.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.actual-api-private.tls: "true"
      traefik.http.routers.actual-api-private.tls.certresolver: "cf_dns"
      traefik.http.routers.actual-api-private.service: "actual-api-private"
      traefik.http.services.actual-api-private.loadbalancer.server.port: "5007"
      traefik.docker.network: "traefik-proxy"

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
  traefik_proxy_network:
    name: traefik-proxy
    external: true
