services:
  blender:
    image: ghcr.io/linuxserver/blender:latest
    container_name: blender
    hostname: blender
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.000.0.1 8082 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${DOCKER_CONFIG_DIR}/blender:/config:rw
      - ${DOCKER_DATA_DIR}/blender/projects:/projects:rw
    environment:
      TZ: "${TZ}"
      CUSTOM_USER: "${ADMIN_USER}"
      PASSWORD: "${PASSWORD}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      TITLE: Blender
      FILE_MANAGER_PATH: /projects
      WEBPUI_PORT: 8082
    restart: unless-stopped

    networks:
      - cloudflare_web_network

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
