services:
    excalidraw:
        image: excalidraw/excalidraw:latest
        container_name: excalidraw
        restart: unless-stopped
        stdin_open: true
        environment:
            - NODE_ENV=production
        labels:
            traefik.enable: "true"
            traefik.http.routers.excalidraw.rule: "Host(`${EXCALIDRAW_SUBDOMAIN}.${DOMAIN}`)"
            traefik.http.routers.excalidraw.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
            traefik.http.routers.excalidraw.tls: "true"
            traefik.http.routers.excalidraw.tls.certresolver: "cf_dns"
            traefik.http.routers.excalidraw.service: "excalidraw"
            traefik.http.services.excalidraw.loadbalancer.server.port: "80"
            traefik.docker.network: "traefik-proxy"
        networks:
            - cloudflare_web_network
            - traefik_proxy_network

networks:
    cloudflare_web_network:
        name: cloudflare-web
        external: true
    traefik_proxy_network:
        name: traefik-proxy
        external: true
