services:
  convertx:
    image: ghcr.io/c4illin/convertx:latest
    container_name: Convertx
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: "${TZ}"
      JWT_SECRET: "${JWT_SECRET}"
      ACCOUNT_REGISTRATION: "false"
      HTTP_ALLOWED: "true"
      ALLOW_UNAUTHENTICATED: "false"
    volumes:
      - ${DOCKER_DATA_DIR}/convertx:/app/data:rw
    labels:
      traefik.enable: "true"
      traefik.http.routers.convertx.rule: "Host(`${CONVERTX_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.convertx.entrypoints: "${TRAEFIK_ENTRYPOINT_3}"
      traefik.http.routers.convertx.tls: "true"
      traefik.http.routers.convertx.tls.certresolver: "cf_dns"
      traefik.http.routers.convertx.service: "convertx"
      traefik.http.services.convertx.loadbalancer.server.port: "3000"
      traefik.docker.network: "traefik-proxy"
    networks:
      - cloudflare_web_network
      - traefik_proxy_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
  traefik_proxy_network:
    name: traefik-proxy
    external: true
