services:
  convertx:
    image: ghcr.io/c4illin/convertx:latest
    container_name: Convertx
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: "${TZ}"
      JWT_SECRET: "${JWT_SECRET}"
      ACCOUNT_REGISTRATION: "false"
      HTTP_ALLOWED: "true"
      ALLOW_UNAUTHENTICATED: "false"
    volumes:
      - ${DOCKER_DATA_DIR}/convertx:/app/data:rw
    networks:
      - cloudflare_web_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  cloudflare_web_network:
    name: cloudflare-web
    external: true
