services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped

    group_add:
      - "121"

    # Used for the community widget. Comment out the one not in use
    # https://github.com/glanceapp/community-widgets/tree/main
    environment:

      - UPTIME_KUMA_URL=${UPTIME_KUMA_URL}
      - UPTIME_KUMA_PUBLIC_URL=${UPTIME_KUMA_PUBLIC_URL}
      - UPTIME_KUMA_STATUS_SLUG=${UPTIME_KUMA_STATUS_SLUG}

      - IMMICH_URL=${IMMICH_URL}
      - IMMICH_API_KEY=${IMMICH_API_KEY}

      - BESZEL_URL=${BESZEL_URL}
      - BESZEL_TOKEN=${BESZEL_TOKEN}

      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_PUBLIC_URL=${JELLYFIN_PUBLIC_URL}
      - JELLYFIN_KEY=${JELLYFIN_KEY}

      - KAVITA_URL=${KAVITA_URL}
      - KAVITA_PUBLIC_URL=${KAVITA_PUBLIC_URL}
      - KAVITA_KEY=${KAVITA_KEY}

      - AUDIOBOOKSHELF_URL=${AUDIOBOOKSHELF_URL}
      - AUDIOBOOKSHELF_PUBLIC_URL=${AUDIOBOOKSHELF_PUBLIC_URL}
      - AUDIOBOOKSHELF_KEY=${AUDIOBOOKSHELF_KEY}

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}

    volumes:
      - ${DOCKER_CONFIG_DIR}/glance/config:/app/config
      - ${DOCKER_CONFIG_DIR}/glance/assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - cloudflare_web_network

networks:
  cloudflare_web_network:
    external: true
    name: cloudflare-web
